services:
  - type: worker
    name: spyware-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free # ya paid plan
    region: oregon
